package scenariocontext;

public enum FormKey {
    CONTACT_FIRST_NAME,
    CONTACT_LAST_NAME,
    CONTACT_DATE_OF_BIRTH,
    CONTACT_EMAIL,
    CONTACT_PHONE,
    CONTACT_STREET_ADDR1,
    CONTACT_STREET_ADDR2,
    CONTACT_CITY,
    CONTACT_STATE_OR_PROVINCE,
    CONTACT_POSTAL_CODE,
    CONTACT_COUNTRY
}